services:
  broker:
    container_name: broker
    build:
        context: .
        dockerfile: council-broker.Dockerfile
    ports:
      - 61616:61616

  integrations-rewritten:
    container_name: rewritten-integration
    build:
      context: .
      dockerfile: council-rewritten-integration.Dockerfile
    environment:
      - BROKER_HOST=tcp://broker:61616
      - spring.activemq.broker-url=tcp://broker:61616
    depends_on:
      - broker

  database:
    container_name: database
    build:
      context: .
      dockerfile: council-database.Dockerfile
    ports:
      - 9898:9898

  discord:
    container_name: discord
    build:
      context: .
      dockerfile: council-discord.Dockerfile
    environment:
      - BROKER_HOST=tcp://broker:61616
      - spring.activemq.broker-url=tcp://broker:61616
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - GRPC_ADDRESS=static://database:9898
    depends_on:
        - broker
        - integrations-rewritten
        - database