services:
  database:
    container_name: database
    build:
      context: .
      dockerfile: council-database.Dockerfile
    environment:
      - BROKER_HOST=tcp://broker:61616
      - spring.activemq.broker-url=tcp://broker:61616
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
    ports:
      - 9898:9898

  broker:
    container_name: broker
    image: symptoma/activemq:latest
    environment:
      - ACTIVEMQ_USERNAME=admin
      - ACTIVEMQ_PASSWORD=admin
      - ACTIVEMQ_WEBADMIN_USERNAME=admin
      - ACTIVEMQ_WEBADMIN_PASSWORD=admin
    ports:
      - 61616:61616
      - 8161:8161

  integrations-rewritten:
    container_name: rewritten-integration
    build:
      context: .
      dockerfile: council-rewritten-integration.Dockerfile
    environment:
      - BROKER_HOST=tcp://broker:61616
      - spring.activemq.broker-url=tcp://broker:61616
    depends_on:
      - broker

  toonstats:
    container_name: toonstats
    build:
      context: .
      dockerfile: council-toonstats.Dockerfile
    environment:
      - BROKER_HOST=tcp://broker:61616
      - spring.activemq.broker-url=tcp://broker:61616
    depends_on:
      - broker