services:
  broker:
    container_name: broker
    image: symptoma/activemq:latest
    environment:
      - ACTIVEMQ_USERNAME=admin
      - ACTIVEMQ_PASSWORD=admin
      - ACTIVEMQ_WEBADMIN_USERNAME=admin
      - ACTIVEMQ_WEBADMIN_PASSWORD=admin
    ports:
      - 61616:61616
      - 8161:8161

  integrations-rewritten:
    container_name: rewritten-integration
    build:
      context: .
      dockerfile: council-rewritten-integration.Dockerfile
    environment:
      - BROKER_HOST=tcp://broker:61616
      - spring.activemq.broker-url=tcp://broker:61616
    depends_on:
      - broker

  discord:
    container_name: discord
    build:
      context: .
      dockerfile: council-discord.Dockerfile
    environment:
      - BROKER_HOST=tcp://broker:61616
      - spring.activemq.broker-url=tcp://broker:61616
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DATABASE_URL=http://database:9898
    depends_on:
        - broker
        - integrations-rewritten