broadcast:
  rate: ${BROADCAST_RATE:60000}

topics:
  news: activemq:topic:${NEWS_TOPIC:NewsTopic}
  districts: activemq:topic:${DISTRICTS_TOPIC:DistrictsTopic}
  release-notes: activemq:topic:${RELEASE_NOTES_TOPIC:ReleaseNotesTopic}
  field-offices: activemq:topic:${FIELD_OFFICES_TOPIC:FieldOfficesTopic}
  status: activemq:topic:${STATUS_TOPIC:StatusTopic}

camel:
  springboot:
    main-run-controller: true